stages:
  - deploy

# Sử dụng image Node.js
image: node:20 # Hoặc phiên bản Node.js mà bạn cần

# Step deploy
deploy:
  stage: deploy
  script:
    - echo "Deploying to VPS..."
    - ssh -p 2018 root@103.97.126.52 "cd ~/be-datn-nestjs && \
        echo 'Removing old node_modules...' && \
        rm -rf node_modules/ && \
        echo 'Pulling latest code...' && \
        git pull && \
        echo 'Installing dependencies...' && \
        npm install && \
        npx prisma db push && \
        echo 'Starting the server...' && \
        npm run start"
  only:
    - main # Chỉ deploy khi có thay đổi trên nhánh main
