stages:
  - deploy

# Sử dụng image Node.js
image: node:20 # Hoặc phiên bản Node.js mà bạn cần

# Step deploy
deploy:
  stage: deploy

  script:
    - echo "Deploying to VPS..."
    - apt-get update -y
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ls -a
    - ssh -tt -o StrictHostKeyChecking=no -p 2018 root@103.97.126.52 'bash -s' < deploy.sh
#     - ssh -tt -o StrictHostKeyChecking=no -p 2018 root@103.97.126.52 <<- 'EOF'
# cd be-datn-nestjs
# ls -a
# npm -v
# node -v
# rm -rf node_modules
# git checkout develop
# git pull
# npm install
# npx prisma db push
# npm run dev
# EOF
  only:
    - main
